Revert "chore(deps): update dependency uvicorn to v0.18.1 (#127)" (#130)
This reverts commit be0354c463be309d7b798f79060b68c132b594f1.

AttributeError: module 'uvicorn' has no attribute 'logging'. Did you mean: '_logging'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/logging/config.py", line 392, in resolve
    self.importer(used)
ModuleNotFoundError: No module named 'uvicorn.logging'

Signed-off-by: Christian Berendt <berendt@osism.tech>